# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d2982983f0e17902c2851dcc5037cfb45f60f715df819b694ec63ff0fa6dfa106af08894e5c34493bfb2c5585b4515f97c22a7c7506ff042e0c213177617fca

test:
  secret_key_base: 595440786573ff01e1a8713b64247ece03103d2cf3f7595d656c2206b8763e2f7b8503219f2e9a9821502feb107b16dceb67d37c50b55c0681885af1efad4636

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
